/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package AppPackage;

import java.sql.DriverManager;
import javax.swing.JOptionPane;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;

/**
 *
 * @author JD
 */
public class HospitalGUI extends javax.swing.JFrame {

    /**
     * Creates new form HospitalGUI
     */
    public HospitalGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jDialog1 = new javax.swing.JDialog();
        resetPrompt = new javax.swing.JLabel();
        resetNo = new javax.swing.JButton();
        resetYes = new javax.swing.JButton();
        resetCancel = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lastName = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        firstName = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        dept = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        sampleId = new javax.swing.JTextField();
        signOut = new javax.swing.JRadioButton();
        returnSample = new javax.swing.JRadioButton();
        reset = new javax.swing.JButton();
        submit = new javax.swing.JButton();
        jCheckBox1 = new javax.swing.JCheckBox();
        jLabel8 = new javax.swing.JLabel();
        emailAddress = new javax.swing.JTextField();

        jDialog1.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        resetPrompt.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        resetPrompt.setText("Are You Sure You Want to Clear All Fields?");
        jDialog1.getContentPane().add(resetPrompt, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 50, -1, -1));

        resetNo.setText("No");
        resetNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetNoActionPerformed(evt);
            }
        });
        jDialog1.getContentPane().add(resetNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 130, 60, -1));

        resetYes.setText("Yes");
        jDialog1.getContentPane().add(resetYes, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 60, -1));

        resetCancel.setText("Cancel");
        jDialog1.getContentPane().add(resetCancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 130, -1, -1));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sample Tracker v1.0");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Please fill in your information below and scan your sample");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 360, 40));

        jLabel2.setText("Sample ID:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, 100, 20));

        lastName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lastNameActionPerformed(evt);
            }
        });
        getContentPane().add(lastName, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 80, 230, -1));

        jLabel3.setText("First Name:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 90, 20));

        jLabel4.setText("Last Name:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 90, 20));

        firstName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                firstNameActionPerformed(evt);
            }
        });
        getContentPane().add(firstName, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 50, 230, -1));

        jLabel5.setText("Department:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 100, 20));

        dept.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deptActionPerformed(evt);
            }
        });
        getContentPane().add(dept, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 110, 230, -1));

        jLabel6.setText("Please select the one that applies:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, 220, 20));

        sampleId.setEditable(false);
        sampleId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sampleIdActionPerformed(evt);
            }
        });
        getContentPane().add(sampleId, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 170, 230, -1));

        buttonGroup1.add(signOut);
        signOut.setText("Sign out sample");
        signOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signOutActionPerformed(evt);
            }
        });
        getContentPane().add(signOut, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 220, 140, 20));

        buttonGroup1.add(returnSample);
        returnSample.setText("Return sample");
        getContentPane().add(returnSample, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 220, -1, 20));

        reset.setText("Reset");
        reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetActionPerformed(evt);
            }
        });
        getContentPane().add(reset, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 260, 70, -1));

        submit.setText("Submit");
        submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitActionPerformed(evt);
            }
        });
        getContentPane().add(submit, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 260, -1, -1));

        jCheckBox1.setText("Check to enter manually");
        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });
        getContentPane().add(jCheckBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 170, -1, 20));

        jLabel8.setText("Email:");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, -1, -1));

        emailAddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailAddressActionPerformed(evt);
            }
        });
        getContentPane().add(emailAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 140, 230, -1));

        setSize(new java.awt.Dimension(545, 355));
        setLocationRelativeTo(null);
    }// </editor-fold>                        

    private void lastNameActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
    }                                        

    private void firstNameActionPerformed(java.awt.event.ActionEvent evt) {                                          
        // TODO add your handling code here:
    }                                         

    private void deptActionPerformed(java.awt.event.ActionEvent evt) {                                     
        // TODO add your handling code here:
    }                                    

    private void sampleIdActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
    }                                        

    private void resetActionPerformed(java.awt.event.ActionEvent evt) {                                      
        firstName.setText("");
        lastName.setText("");
        sampleId.setText("");        
        dept.setText("");
        emailAddress.setText("");
    }                                     

    private void signOutActionPerformed(java.awt.event.ActionEvent evt) {                                        
        // TODO add your handling code here:
    }                                       

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {                                           
        if (sampleId.isEditable()) {
            sampleId.setEditable(false);
            sampleId.setText("");
        }
        else {
            sampleId.setEditable(true);
        }        
    }                                          

    private void submitActionPerformed(java.awt.event.ActionEvent evt) {                                       
        // TODO add your handling code here:
        String first = firstName.getText();
        String last = lastName.getText();
        String department = dept.getText();
        String sample = sampleId.getText();
        String emailAdress = emailAddress.getText();
        
        try {
            Class.forName("com.mysql.jdbc.Driver");
	} catch (ClassNotFoundException e) {
            e.printStackTrace();
            System.out.println("Did you forget to include the JAR file in the project?");
	}
        //to establish a database connection we need several pieces of information
        String databaseURI = "jdbc:mysql://zenit.senecac.on.ca/bif724_161a12";
        
        //queries in Java
        String insertQuery1 = "INSERT INTO client_id VALUES ('', first, last, emailAdress, department)";
        String insertQuery2 = "INSERT INTO main_table VALUES ('', '', '', '', '', 'sample')";
        String insertQuery3 = "INSERT INTO barcode_id VALUES ('sample')";
        
        //Declare references for the objects we're going to use:
	Connection conn = null;
	Statement stmt = null;
	ResultSet records = null;
        
        //Instantiate the database connection
        String username = "bif724_161a12";
        String password = "erZJ5526";
	boolean connected = false;
	System.out.println("Attempting to connect to database: " + databaseURI + " with username: " + username + " password: " + password);
	try {
            conn = DriverManager.getConnection(databaseURI, username, password);
            stmt = conn.createStatement();
            connected = true;
	} catch (SQLException e) {
            e.printStackTrace();
            connected = false;
	}
	if(connected == true){	
            //another example: insert a record
            System.out.println("Inserting a record into the table");
            try {
		//NOTE: we're using executeUpdate! to modify the table
		stmt.executeUpdate(insertQuery1);
                stmt.executeUpdate(insertQuery2);
                stmt.executeUpdate(insertQuery3);
		//use the same loop to display the updated table
		while(records.next()){
                    int id = records.getInt("user_id");
                    String firstname = records.getString("first_name");
                    String lastname = records.getString("last_name");
                    String email = records.getString("email");
                    String departmentRecord = records.getString("department");
                    System.out.println("user id: " + id + " firstname: " + firstname + " lastname: "+ lastname + " email: " + email + " department: " + departmentRecord);
		}
                //Dialog confirmation box
                JOptionPane.showMessageDialog(jDialog1,
                "Information has been submitted. Email has been sent as confirmation.");
            } catch (SQLException e) {
		e.printStackTrace();
            }
        }
    }                                      

    private void emailAddressActionPerformed(java.awt.event.ActionEvent evt) {                                             
        // TODO add your handling code here:
    }                                            

    private void resetNoActionPerformed(java.awt.event.ActionEvent evt) {                                        
        // TODO add your handling code here:
        
    }                                       

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HospitalGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HospitalGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HospitalGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HospitalGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HospitalGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JTextField dept;
    private javax.swing.JTextField emailAddress;
    private javax.swing.JTextField firstName;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField lastName;
    private javax.swing.JButton reset;
    private javax.swing.JButton resetCancel;
    private javax.swing.JButton resetNo;
    private javax.swing.JLabel resetPrompt;
    private javax.swing.JButton resetYes;
    private javax.swing.JRadioButton returnSample;
    private javax.swing.JTextField sampleId;
    private javax.swing.JRadioButton signOut;
    private javax.swing.JButton submit;
    // End of variables declaration                   
}
